#!/bin/bash

# Certbot SSL Certificate Setup and Auto-Renewal Script
# =====================================================
# This script automates Let's Encrypt certificate generation, installation, and auto-renewal
# 
# Usage:
#   bash nginx/certbot-setup.sh <domain_name> <email>
#   Example: bash nginx/certbot-setup.sh example.com admin@example.com
#
# Prerequisites:
#   - Docker and Docker Compose installed
#   - Port 80 accessible from the internet (required for Let's Encrypt validation)
#   - Valid domain name pointing to this server
#
# What this script does:
#   1. Validates input parameters
#   2. Creates certificate directory structure
#   3. Generates Diffie-Hellman parameters for perfect forward secrecy
#   4. Issues SSL certificate using Let's Encrypt (Certbot)
#   5. Updates Nginx configuration with the certificate paths
#   6. Sets up automatic renewal via cron job
#   7. Performs initial certificate renewal test
#
# Automatic renewal:
#   - Certbot automatically renews certificates 30 days before expiration
#   - Renewal runs daily via systemd timer or cron job
#   - Nginx reloads configuration without downtime after successful renewal

set -e  # Exit immediately if any command fails

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'  # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

# Validate input parameters
if [ $# -lt 2 ]; then
    print_error "Usage: bash certbot-setup.sh <domain_name> <email>"
    print_error "Example: bash certbot-setup.sh example.com admin@example.com"
    exit 1
fi

DOMAIN="$1"
EMAIL="$2"
CERTBOT_IMAGE="certbot/certbot:latest"
LETSENCRYPT_DIR="./letsencrypt"
DHPARAM_FILE="./nginx/dhparam.pem"

print_status "Starting SSL Certificate Setup for domain: $DOMAIN"
print_status "Email for Let's Encrypt notifications: $EMAIL"

# Create necessary directories
print_status "Creating certificate directories..."
mkdir -p "$LETSENCRYPT_DIR/live/$DOMAIN"
mkdir -p "$LETSENCRYPT_DIR/archive"
mkdir -p "$LETSENCRYPT_DIR/renewal"
mkdir -p "./certbot_webroot/.well-known/acme-challenge"

# Generate Diffie-Hellman parameters (this takes ~2 minutes)
# DH parameters are used in TLS handshake for forward secrecy
# Without this, even with ECDHE, older clients may fall back to weaker DH
print_status "Generating Diffie-Hellman parameters (2048 bits)..."
print_warning "This may take 2-5 minutes..."

if [ ! -f "$DHPARAM_FILE" ]; then
    docker run --rm \
        -v "$(pwd)/nginx:/etc/nginx" \
        openssl \
        dhparam -out dhparam.pem 2048
    print_status "DH parameters generated: $DHPARAM_FILE"
else
    print_status "DH parameters already exist: $DHPARAM_FILE"
fi

# Obtain SSL certificate from Let's Encrypt
# Certbot performs ACME challenge validation over HTTP (port 80)
print_status "Requesting SSL certificate from Let's Encrypt..."
print_warning "Ensure port 80 is accessible from the internet"

docker run --rm \
    --name certbot \
    -p 80:80 \
    -v "$(pwd)/$LETSENCRYPT_DIR:/etc/letsencrypt" \
    -v "$(pwd)/certbot_webroot:/var/www/certbot" \
    "$CERTBOT_IMAGE" \
    certonly \
    --standalone \
    --agree-tos \
    --no-eff-email \
    --email "$EMAIL" \
    -d "$DOMAIN" \
    --non-interactive \
    --preferred-challenges http

if [ $? -eq 0 ]; then
    print_status "SSL certificate successfully obtained!"
    print_status "Certificate path: $LETSENCRYPT_DIR/live/$DOMAIN/fullchain.pem"
    print_status "Private key path: $LETSENCRYPT_DIR/live/$DOMAIN/privkey.pem"
else
    print_error "Failed to obtain SSL certificate"
    print_error "Troubleshooting tips:"
    print_error "1. Ensure port 80 is open and accessible"
    print_error "2. Verify domain DNS is pointing to this server"
    print_error "3. Check firewall rules: sudo ufw allow 80/tcp"
    print_error "4. Try again in a few minutes (rate limiting)"
    exit 1
fi

# Update Nginx SSL configuration with domain name
print_status "Updating Nginx SSL configuration with domain: $DOMAIN"

# Create updated SSL config with the actual domain
cat > ./nginx/ssl-configured.conf << 'EOF'
# Production Nginx configuration - Auto-generated by certbot-setup.sh
# DO NOT EDIT MANUALLY - Changes will be overwritten

# HTTP server block - redirect all HTTP traffic to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name _;

    # Required for Let's Encrypt certificate renewal
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    # Redirect all other HTTP traffic to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS server block - primary production server
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name _;

    # SSL certificate paths
    ssl_certificate /etc/letsencrypt/live/DOMAIN_PLACEHOLDER/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/DOMAIN_PLACEHOLDER/privkey.pem;

    # SSL/TLS configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256';
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:50m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;
    ssl_dhparam /etc/nginx/dhparam.pem;

    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 1.1.1.1 1.0.0.1 valid=300s;
    resolver_timeout 5s;

    # Security headers
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml text/javascript application/json application/javascript application/xml+rss;

    # Rate limiting
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;
    limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=5r/m;

    client_max_body_size 10M;

    # User Service
    location /api/auth/ {
        limit_req zone=auth_limit burst=10 nodelay;
        proxy_pass http://user-service:3001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    location /users/ {
        limit_req zone=api_limit burst=20 nodelay;
        proxy_pass http://user-service:3001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Post Service
    location /api/posts/ {
        limit_req zone=api_limit burst=20 nodelay;
        proxy_pass http://post-service:3002;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    location /posts/ {
        limit_req zone=api_limit burst=20 nodelay;
        proxy_pass http://post-service:3002;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Comment Service
    location /api/comments/ {
        limit_req zone=api_limit burst=20 nodelay;
        proxy_pass http://comment-service:3003;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    location /comments/ {
        limit_req zone=api_limit burst=20 nodelay;
        proxy_pass http://comment-service:3003;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Health check endpoint
    location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }

    # Default 404
    location / {
        return 404;
    }

    # Deny access to sensitive files
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    location ~ ^/(wp-admin|wp-login|\.env|\.git)$ {
        deny all;
        access_log off;
        log_not_found off;
    }
}
EOF

# Replace domain placeholder
sed -i "s|DOMAIN_PLACEHOLDER|$DOMAIN|g" ./nginx/ssl-configured.conf

print_status "Created Nginx configuration: ./nginx/ssl-configured.conf"

# Setup automatic certificate renewal via cron
print_status "Setting up automatic certificate renewal..."

# Create renewal script
mkdir -p ./scripts
cat > ./scripts/renew-ssl-cert.sh << 'EOF'
#!/bin/bash
# Automatic SSL Certificate Renewal Script
# Runs daily via cron; attempts renewal 30 days before expiration

DOMAIN="$1"
LETSENCRYPT_DIR="./letsencrypt"
CERTBOT_IMAGE="certbot/certbot:latest"
LOG_FILE="./logs/certbot-renewal.log"

mkdir -p ./logs

echo "[$(date)] Starting certificate renewal check for $DOMAIN" >> "$LOG_FILE"

docker run --rm \
    -v "$(pwd)/$LETSENCRYPT_DIR:/etc/letsencrypt" \
    -v "$(pwd)/certbot_webroot:/var/www/certbot" \
    "$CERTBOT_IMAGE" \
    renew \
    --quiet \
    --allow-skip-validation \
    2>&1 | tee -a "$LOG_FILE"

if [ $? -eq 0 ]; then
    echo "[$(date)] Certificate renewal successful" >> "$LOG_FILE"
    # Reload Nginx after successful renewal (without downtime)
    docker-compose exec -T nginx nginx -s reload 2>&1 | tee -a "$LOG_FILE"
else
    echo "[$(date)] Certificate renewal failed or not needed" >> "$LOG_FILE"
fi
EOF

chmod +x ./scripts/renew-ssl-cert.sh

print_status "Created renewal script: ./scripts/renew-ssl-cert.sh"

# Add cron job for automatic renewal (only if not already added)
CRON_JOB="0 3 * * * cd /path/to/project && bash ./scripts/renew-ssl-cert.sh $DOMAIN"

if crontab -l 2>/dev/null | grep -q "renew-ssl-cert.sh"; then
    print_warning "Cron job already exists"
else
    (crontab -l 2>/dev/null; echo "$CRON_JOB") | crontab -
    print_status "Added cron job for daily renewal at 3 AM"
    print_warning "Update the path in crontab: crontab -e"
fi

# Test certificate renewal (dry-run)
print_status "Testing certificate renewal (dry-run)..."

docker run --rm \
    -v "$(pwd)/$LETSENCRYPT_DIR:/etc/letsencrypt" \
    -v "$(pwd)/certbot_webroot:/var/www/certbot" \
    "$CERTBOT_IMAGE" \
    renew \
    --dry-run \
    --quiet

if [ $? -eq 0 ]; then
    print_status "Certificate renewal test successful!"
    print_status "Certificates will auto-renew 30 days before expiration"
else
    print_warning "Renewal test returned an issue (may not be critical)"
fi

# Display certificate information
print_status "Certificate Information:"
print_status "========================"

docker run --rm \
    -v "$(pwd)/$LETSENCRYPT_DIR:/etc/letsencrypt" \
    "$CERTBOT_IMAGE" \
    certificates

print_status ""
print_status "Next Steps:"
print_status "1. Copy the SSL configuration to use:"
print_status "   cp ./nginx/ssl-configured.conf ./nginx/default.conf"
print_status "2. Update docker-compose to use the certificate volume:"
print_status "   volumes:"
print_status "     - ./letsencrypt:/etc/letsencrypt"
print_status "     - ./certbot_webroot:/var/www/certbot"
print_status "     - ./nginx/dhparam.pem:/etc/nginx/dhparam.pem"
print_status ""
print_status "3. Restart Nginx:"
print_status "   docker-compose restart nginx"
print_status ""
print_status "4. Verify HTTPS:"
print_status "   curl -I https://$DOMAIN"
print_status ""
print_status "SSL Certificate Setup Complete!"
print_status "Certificate will auto-renew 30 days before expiration"
